// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: OmnitrixUI

#ifndef _OMNITRIXUI_UI_H
#define _OMNITRIXUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen0.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * progress_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_launchanim0001_png);    // assets/launchAnim0001.png
LV_IMG_DECLARE(ui_img_launchanim0002_png);    // assets/launchAnim0002.png
LV_IMG_DECLARE(ui_img_launchanim0003_png);    // assets/launchAnim0003.png
LV_IMG_DECLARE(ui_img_launchanim0004_png);    // assets/launchAnim0004.png
LV_IMG_DECLARE(ui_img_launchanim0005_png);    // assets/launchAnim0005.png
LV_IMG_DECLARE(ui_img_launchanim0006_png);    // assets/launchAnim0006.png
LV_IMG_DECLARE(ui_img_launchanim0007_png);    // assets/launchAnim0007.png
LV_IMG_DECLARE(ui_img_launchanim0008_png);    // assets/launchAnim0008.png
LV_IMG_DECLARE(ui_img_launchanim0009_png);    // assets/launchAnim0009.png
LV_IMG_DECLARE(ui_img_launchanim0010_png);    // assets/launchAnim0010.png
LV_IMG_DECLARE(ui_img_launchanim0011_png);    // assets/launchAnim0011.png
LV_IMG_DECLARE(ui_img_launchanim0012_png);    // assets/launchAnim0012.png
LV_IMG_DECLARE(ui_img_launchanim0013_png);    // assets/launchAnim0013.png
LV_IMG_DECLARE(ui_img_launchanim0014_png);    // assets/launchAnim0014.png
LV_IMG_DECLARE(ui_img_diamondhead_png);    // assets/diamondhead.png
LV_IMG_DECLARE(ui_img_fourarms_png);    // assets/fourarms.png
LV_IMG_DECLARE(ui_img_ghostfreak_png);    // assets/ghostfreak.png
LV_IMG_DECLARE(ui_img_greymatter_png);    // assets/greymatter.png
LV_IMG_DECLARE(ui_img_heatblast_png);    // assets/heatblast.png
LV_IMG_DECLARE(ui_img_ripjaws_png);    // assets/ripjaws.png
LV_IMG_DECLARE(ui_img_stinkfly_png);    // assets/stinkfly.png
LV_IMG_DECLARE(ui_img_tuna_png);    // assets/tuna.png
LV_IMG_DECLARE(ui_img_upgrade_png);    // assets/upgrade.png
LV_IMG_DECLARE(ui_img_wildmutt_png);    // assets/wildmutt.png
LV_IMG_DECLARE(ui_img_xlr8_png);    // assets/xlr8.png
LV_IMG_DECLARE(ui_img_diamondhead_holo_png);    // assets/diamondhead_holo.png
LV_IMG_DECLARE(ui_img_fourarms_holo_png);    // assets/fourarms_holo.png
LV_IMG_DECLARE(ui_img_ghostfreak_holo_png);    // assets/ghostfreak_holo.png
LV_IMG_DECLARE(ui_img_greymatter_holo_png);    // assets/greymatter_holo.png
LV_IMG_DECLARE(ui_img_heatblast_holo_png);    // assets/heatblast_holo.png
LV_IMG_DECLARE(ui_img_ripjaws_holo_png);    // assets/ripjaws_holo.png
LV_IMG_DECLARE(ui_img_stinkfly_holo_png);    // assets/stinkfly_holo.png
LV_IMG_DECLARE(ui_img_tuna_holo_png);    // assets/tuna_holo.png
LV_IMG_DECLARE(ui_img_upgrade_holo_png);    // assets/upgrade_holo.png
LV_IMG_DECLARE(ui_img_wildmutt_holo_png);    // assets/wildmutt_holo.png
LV_IMG_DECLARE(ui_img_xlr8_holo_png);    // assets/xlr8_holo.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
