// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: OmnitrixUI

#include "ui.h"

lv_obj_t * ui_Screen0 = NULL;
lv_obj_t * ui_launchAnim = NULL;
lv_obj_t * ui_alien = NULL;
// event funtions

// build funtions

void ui_Screen0_screen_init(void)
{
    ui_Screen0 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_launchAnim = lv_img_create(ui_Screen0);
    lv_img_set_src(ui_launchAnim, &ui_img_launchanim0001_png);
    lv_obj_set_width(ui_launchAnim, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_launchAnim, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_launchAnim, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_launchAnim, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_launchAnim, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alien = lv_img_create(ui_Screen0);
    lv_obj_set_width(ui_alien, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alien, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alien, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alien, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_alien, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen0_screen_destroy(void)
{
    if(ui_Screen0) lv_obj_del(ui_Screen0);

    // NULL screen variables
    ui_Screen0 = NULL;
    ui_launchAnim = NULL;
    ui_alien = NULL;

}
